name: "Black Myth Wukong"
type: "steam"
app_id: "3132990"
exe_name: "b1-Win64-Shipping.exe.exe"
process_name: "b1"
launch_options: " "
startup_time: 60

workflow:
  # ===== GAME LAUNCH =====
  #1
  - action: "launch_game"
  
  #2
  - action: "wait_for_game"
    timeout: 60

  #3
  - action: "wait"
    seconds: 30

  # ===== WAIT FOR MAIN MENU =====
  #4
  - action: "wait_for_template"
    template: "main_menu.png"
    timeout: 90
    threshold: 0.90
  
  #5
  - action: "take_screenshot"
    name: "01_main_menu_loaded"

  # ===== NAVIGATE TO BENCHMARK =====
  #6
  - action: "click_template"
    template: "main_menu.png"
    timeout: 10

  
  #7
  - action: "wait_for_template"
    template: "benchmark_button.png"
    timeout: 60
  
  #8
  - action: "take_screenshot"
    name: "02_benchmark_option_menu_seen"
    delay: 2

  #9
  - action: "click_template"
    template: "benchmark_button.png"
    timeout: 10
    threshold: 0.90
  
  #10
  - action: "take_screenshot"
    name: "03_after_benchmark_click"
    delay: 1
  
# ===== WAIT FOR POP UP and click confirm =====
# click Confirm - "Are you sure you want to run benchmark" Dialog box
  #11
  - action: "click_template"
    template: "confirm_button.png"
    timeout: 10
    threshold: 0.90

  #12
  - action: "take_screenshot"
    name: "04_benchmark_loading"
# Wait for loading screen to finish and benchmark to actually begin
  #13
  - action: "wait_for_template"
    template: "benchmark_start.png"
    timeout: 120
    threshold: 0.90  # Lower threshold if needed  
# Mark benchmark start time (workflow engine will log timestamp)
  #14
  - action: "log_message"
    message: "BENCHMARK_START_TIME"

  #15
  - action: "take_screenshot"
    name: "05_benchmark_start_detected"


# ===== WAIT FOR BENCHMARK COMPLETION =====
  # Wait for benchmark to complete (detect end screen/results)
  #16
  - action: "wait_for_template"
    template: "benchmark_end.png" 
    timeout: 300  # Max 5 minutes for benchmark
    threshold: 0.83
  
  # Mark benchmark end time
  #17
  - action: "log_message"
    message: "BENCHMARK_END_TIME"
  
  #18
  - action: "take_screenshot"
    name: "06_benchmark_end_detected"

  #19
  # Wait for results to stabilize
  - action: "wait"
    seconds: 10


# ===== CAPTURE FINAL RESULTS =====
  #20
  - action: "take_screenshot"
    name: "07_results_capture"

# Wait to review results
  #21
  - action: "wait"
    seconds: 10

# ===== EXIT BENCHMARK RESULTS =====  

  #22
  - action: "press_key"
    key: "escape"
    delay: 2

  #23
  - action: "take_screenshot"
    name: "08_benchmark_quit_dialog"

  #24
  - action: "click_template"
    template: "confirm_button.png"
    timeout: 10
    threshold: 0.90
    delay: 2

  #25
  - action: "take_screenshot"
    name: "09_going_back_main_menu"

  # ===== WAIT FOR MAIN MENU =====
  #26
  - action: "wait_for_template"
    template: "main_menu.png"
    timeout: 90
    threshold: 0.90
  
  #27
  - action: "take_screenshot"
    name: "10_main_menu_loaded"

  #28
  - action: "press_key"
    key: "enter"
    delay: 2
  
  # ===== Exit the game =====

  #29
  - action: "take_screenshot"
    name: "11_exit_menu_found"

  
  #30
  - action: "wait_for_template"
    template: "exit_game.png"

  #31
  - action: "click_template"
    template: "exit_game.png"
    threshold: 0.90
    delay: 2
  
  #32
  - action: "take_screenshot"
    template: "12_game_exited"

  #33
  - action: "press_key"
    key: "enter"