name: "CS2"
type: "steam"
app_id: "730"
exe_name: "cs2.exe"
process_name: "cs2"
launch_options: "-novid -console fps_max 0"
startup_time: 60

workflow:
  # ===== GAME LAUNCH =====
  - action: "launch_game"
  
  - action: "wait_for_game"
    timeout: 60

  - action: "wait"
    seconds: 30

  # ===== WAIT FOR MAIN MENU =====
  - action: "wait_for_template"
    template: "main_menu.png"
    timeout: 90
  
  - action: "take_screenshot"
    name: "01_main_menu_loaded"

  # ===== PRESS ESC For removing any pop up ======
  - action: "press_key"
    key: "escape"
    delay: 2

  - action: "press_key"
    key: "escape"
    delay: 2

  # ===== NAVIGATE TO BENCHMARK =====
  - action: "wait_for_template"
    template: "play_button.png"
    timeout: 60
  
  - action: "click_template"
    template: "play_button.png"
    timeout: 10
  
  - action: "take_screenshot"
    name: "02_after_play_click"
  
  - action: "wait_for_template"
    template: "workshop_map.png"
    timeout: 20
  
  - action: "click_template"
    template: "workshop_map.png"
    timeout: 10
  
  - action: "take_screenshot"
    name: "03_workshop_maps_page"
  
  - action: "wait_for_template"
    template: "fps_benchmark_map.png"
    threshold: 0.80
    timeout: 30
  
  - action: "click_template"
    template: "fps_benchmark_map.png"
    timeout: 10
  
  - action: "take_screenshot"
    name: "04_benchmark_map_selected"
  
  - action: "wait_for_template"
    template: "go_button.png"
    timeout: 15
  
  - action: "click_template"
    template: "go_button.png"
    timeout: 10
  
  - action: "take_screenshot"
    name: "05_benchmark_starting"
  
  # ===== WAIT FOR ACTUAL BENCHMARK START =====
  # Wait for loading screen to finish and benchmark to actually begin
  - action: "wait_for_template"
    template: "benchmark_start.png"
    timeout: 120
    threshold: 0.90  # Lower threshold if needed
  
  - action: "take_screenshot"
    name: "06_benchmark_start_detected"
  
  # Mark benchmark start time (workflow engine will log timestamp)
  - action: "log_message"
    message: "BENCHMARK_START_TIME"
  
  # ===== WAIT FOR BENCHMARK COMPLETION =====
  # Wait for benchmark to complete (detect end screen/results)
  - action: "wait_for_template"
    template: "benchmark_end.png" 
    timeout: 300  # Max 5 minutes for benchmark
    threshold: 0.90
  
  # Mark benchmark end time
  - action: "log_message"
    message: "BENCHMARK_END_TIME"
  
  - action: "take_screenshot"
    name: "07_benchmark_end_detected"
  
  # Wait for results to stabilize
  - action: "wait"
    seconds: 20
  
  # ===== CAPTURE FINAL RESULTS =====
  - action: "take_screenshot"
    name: "08_benchmark_results_final"
  
  # Wait to review results
  - action: "wait"
    seconds: 10
  
  # ===== EXIT BENCHMARK =====
  - action: "press_key"
    key: "escape"
    delay: 2

  - action: "click_template_if_exists"
    template: "power_button.png"
    timeout: 10

  - action: "click_template_if_exists"
    template: "quit_button.png"
    timeout: 10
  
 
  - action: "take_screenshot"
    name: "09_workflow_complete"

# Template references (for documentation)
screens:
  main_menu: "templates/screens/cs2/main_menu.png"
  play_button: "templates/screens/cs2/play_button.png"
  workshop_map: "templates/screens/cs2/workshop_map.png"
  fps_benchmark_map: "templates/screens/cs2/fps_benchmark_map.png"
  go_button: "templates/screens/cs2/go_button.png"
  benchmark_start: "templates/screens/cs2/benchmark_start.png"    # NEW: Actual benchmark running
  benchmark_end: "templates/screens/cs2/benchmark_end.png"        # NEW: Benchmark complete/results
  quit_button: "templates/screens/cs2/quit_button.png"
  power_button: "templates/screens/cs2/power_button.png"